### ISSUE TITLE
A few concerns about today's meeting

### ISSUE THREAD

**Issue by yzr1996** [UBC-MDS/group_26#11]
1. Whether we add our proposal on the Readme file directly?
2. Add our team work contract on the repo
3. We could explain briefly about how to share the results of our analysis. For example, finally we would use a table with different scores to show the performance of our model based on the test dataset. 
4. Add a data file in repo

**Comment by Andrew-Tan** [comment]
> Whether we add our proposal on the Readme file directly?

Yes. @arashshams is already doing that in his latest PR.

> Add our team work contract on the repo

Yes. @mmyz88 will do that

> We could explain briefly about how to share the results of our analysis. For example, finally we would use a table with different scores to show the performance of our model based on the test dataset.

Yes. @arashshams will include those in the proposal

> Add a data file in repo

We won't do that for this milestone yet.
