### ISSUE TITLE
Task Distribution for Milestone 2

### ISSUE THREAD

**Issue by mmyz88** [UBC-MDS/group_26#17]
FOUR major tasks for M2:

1. Write a script that reads the downloaded data and performs and data cleaning/pre-processing, transforming, and/or splitting
2. Write a script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that data set
3. Write a script that performs some statistical or machine learning analysis and summarizes the results as a figure(s) and a table(s)
4. Write a literate code document which presents your analysis and findings

I believe @yzr1996 (Eric) has taken task 2, the EDA one. Let's split up the rest here

**Comment by Andrew-Tan** [comment]
The four tasks are a bit inter-related. For example, task 3 is dependent on the data set produced in task 1, and so as task 4 (dependent on task 3). I wonder how should we handle this...

**Comment by mmyz88** [comment]
> The four tasks are a bit inter-related. For example, task 3 is dependent on the data set produced in task 1, and so as task 4 (dependent on task 3). I wonder how should we handle this...

Yea good point. 
I mean 1 & 2 are pretty much ready to go, so if someone can finish 3 quickly, and whoever writes 4 can write up a skeleton first and insert those images later.  What do you think?

**Comment by yzr1996** [comment]
> The four tasks are a bit inter-related. For example, task 3 is dependent on the data set produced in task 1, and so as task 4 (dependent on task 3). I wonder how should we handle this...

Yes, I think task 1 and 2 are somehow independent. I will finish task 2 as soon as I can. As for task 3 and 4, I believe should work together.

**Comment by Andrew-Tan** [comment]
FYI, Tiffany's example project: https://github.com/ttimbers/breast_cancer_predictor

**Comment by arashshams** [comment]
I think it is better that two of us work in parallel on tasks 1 and 3 and then cross-check.

**Comment by mmyz88** [comment]
To summarize our plan (we discussed a little in Zoom), 

- Arash will be mainly in charge of 1, and Kaicheng for 3. These two tasks are closely related and they will be working in parallel and cross check with each other
- Eric will touch up on task 2
- Marco will write up the report for task 4. I will write out the outline first, and fill out the missing materials (graphs, model scores etc) when the first 3 tasks are finalized

**Comment by arashshams** [comment]
Sounds great!
