### ISSUE TITLE
Discussion on Task 1 and 3

### ISSUE THREAD

**Issue by Andrew-Tan** [UBC-MDS/group_26#18]
For milestone 2, task 1 and 3 are pretty inter-related to our point, so while @Andrew-Tan and @arashshams are working in parallel, we should sync up with others what we have done.

This issue is intended to log the conversations.

**Comment by arashshams** [comment]
I will keep in touch Andrew to compare our results of our models.

**Comment by yzr1996** [comment]
Hold on, I found the order of Macro posted about the task is slightly different from the Tiff's one. To be honest, currently I am working on the task1 (Macro's one) or task2 (Tiff's one), 

A second script that reads the data from the first script and performs and data cleaning/pre-processing, transforming, and/or paritionting that needs to happen before exploratory data analysis or modeling takes place. This should take at least two arguments:
a path/filename pointing to the data to be read in
a path/filename pointing to where the cleaned/processed/transformed/paritioned data should live

**Comment by yzr1996** [comment]
Or if you like, I can transfer to do the visualization
