### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/group_26#21]
You should reference the sentiment analysis methodology and talk briefly about it.

**Comment by hsmohammed** [comment]
Your hyperlink to the EDA file is not working.

**Comment by arashshams** [comment]
Hi @Andrew-Tan @yzr1996 @mmyz88  can someone double check the second issue here?

**Comment by arashshams** [comment]
> You should reference the sentiment analysis methodology and talk briefly about it.

Description added in Milestone 2.
