### ISSUE TITLE
Task 2 Discussion

### ISSUE THREAD

**Issue by Andrew-Tan** [UBC-MDS/group_26#26]
We want to combine work for EDA from Eric and Arash. Specifically, we want to include:
- All columns with their types and descriptions
- Review (Text) column. Histogram of most frequent words.
- Authors column, their average ratings visualizations. (@arashsh have done some visualizations)
- Rating (target) column. We want to have a histograms of rating distirbution.
- Correlation between review length and the rating.

**Comment by Andrew-Tan** [comment]
Aside from just the script for task 2, my pull request will also contain the following contents:
- a data/ directory that contains both the raw and processed data (via Eric's pre_process.py)
- a result/ directory that contains the trained model and all the generated visualizations
- a .gitignore file at the root that excluded un-related temporary files

Please do let me know if you have any conern.

**Comment by Andrew-Tan** [comment]
@arashshams I tried fixing the images in your plot with remote images but I was not succeed. For the time being, I'll just leave that out and proceed. We can add that back next week.

**Comment by arashshams** [comment]
Very well Andrew, thank you.
