### ISSUE TITLE
Task list (Week 2020-11-30)

### ISSUE THREAD

**Issue by Andrew-Tan** [UBC-MDS/group_26#31]
- Finish up the make file. @Andrew-Tan 
- We want render our report in our pipeline and put it into make file. @Andrew-Tan 
- Explore other models to see if we have better choices. Each of us should work on 1 model (e.g. tuning the hyperparameters and generate the result scores), and we want to update the report to include our findings. @mmyz88 
  - Ridge @yzr1996 PR: https://github.com/UBC-MDS/group_26/pull/32
  - RandomForestRegressor @arashshams 
  - If we found out either of these models have better result, we should substitute our current one with it.
- Improve visualizations. @arashshams 
- Fix Altair picture generation issue. @Andrew-Tan

**Comment by arashshams** [comment]
Hi @Andrew-Tan , do you need me to start off with your pre-processing code or should I keep my own?

**Comment by mmyz88** [comment]
Final report to update (feel free to add by commenting):

1. add inline reference
2. add models comparison section (replace SVR tuning section)
3. link tables with output files instead of hardcode
4. mention risk of overfitting in criticism
