### ISSUE TITLE
TA Feedback (milestone 2): EDA

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/group_26#39]
EDA should be done using only your training set, not the entire data set.

**Comment by Andrew-Tan** [comment]
@yzr1996 @mmyz88 @arashshams I'll be working on improving the EDA.

I'm going to:
- Address issues we have collected so far
- Improve general appearance of the EDA, by moving more code to the script and reference the result in the report
- Fix issues where prevents images to show up in the rendered html

Please let me know if there are more you want me to work on by replying in this thread.

**Comment by Andrew-Tan** [comment]
This feedback has been addressed
