### ISSUE TITLE
TA Feedback (milestone 2): Part VI Visualization

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/group_26#40]
The visualization in part VI (prediction vs. true ratings) does not appear for me in the notebook containing your report.

**Comment by mmyz88** [comment]
@arashshams @Andrew-Tan @yzr1996 
This is already fixed in the later versions. 

In `Milestone2`, prediction_vs_true figure was an html, and the Jupyter display didn't work apparently. It is now saved as an SVG and it should be working fine.

**Comment by Andrew-Tan** [comment]
In the latest version we had already make sure that it will show up.
