### ISSUE TITLE
TA Feedback (milestone 2): Ordinal -> Numerical conversion?

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/group_26#41]
I suggest you provide some more detailed information in the report about how the ordinal data (sentiment) was converted to numerical so it could be used by your model.

**Comment by mmyz88** [comment]
@jbourak Thanks for your feedback!  I don't think we ever converted `sentiment` to numerical. We used ordinal encoder for it instead.  But our report did miss the part on column transformer, I will add that part in to make it clearer. 

@Andrew-Tan @yzr1996 @arashshams

**Comment by mmyz88** [comment]
Added **Column Transformer** sub-section in Pre-precessing section, and explained how `sentiment` is encoded with Ordinal Encoder, with hyperlink to one-hot encoding.
