### ISSUE TITLE
(Peer Feedback) Level of Detail in README.md and CountVectorizer stop_words 

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/group_26#43]
Hi Group 26, 

I really enjoyed reading your project, it was quite easy to follow along with and it looks like you've done an awesome job on it. 

I have a couple of pieces of feedback listed below:

-  I feel like your README.md could be a little less detailed. Tiff mentioned something along the lines of  README.md should give an overview of your project from a 1000 miles away, and I feel like the Exploratory Data Analysis section in the README.md holds too much details. Specifically the information about what type of visualization you have carried out as part of the EDA can be omitted from the README.md.

- I was wondering if you had tried using the stop_words argument of the CountVectorizer (e.g. `countvectorizer(stop_words='english')`) to filter more uninformative  words such as "the", "of", "and" which would avoid them being construed as signal for prediction.

**Comment by mmyz88** [comment]
Thanks @elabandari! Your feedback is spot on. We are working on incorporating `stop_words` into our analysis.

**Comment by Andrew-Tan** [comment]
We have mostly addressed these issues.
