### ISSUE TITLE
Peer Review Feedback for v0.2.0 release

### ISSUE THREAD

**Issue by KangboLu** [UBC-MDS/group_26#45]
The following feedback is based on the release v0.2.0.  
If you have already updated your repo respecting some of my feedback in future versions> v0.2.0, feel free to ignore the corresponding feedback on v0.2.0.
- Documentation: Is the project properly documented? 
   Yes, it is great. 
- Code: 
  The code is readable. 
  One optional improvement would be:
  For [download_data.csv](https://github.com/UBC-MDS/group_26/blob/0.2.0/src/download_data.py), you can write some error handling code for downloading data. Our group was deducted points because we didn't do it, although it's not required in the written requirement.
- Analysis and reasoning: Is the analysis correct?  
   Yes, it is great. 
   One improvement would always include a baseline model for model comparison. No appearance of the baseline model is mentioned in your report. We don't know if the models perform better than without a complex model or not.
- Communication: 
   Yes, it's easy to follow and the report communicates the findings effectively. Good job!

**Comment by mmyz88** [comment]
Thanks you @KangboLu for the insightful comments, they are really helpful! 
We will discuss among our group to decide whether we include the baseline model.
