### ISSUE TITLE
Instructions to run docker file for testing

### ISSUE THREAD

**Issue by Andrew-Tan** [UBC-MDS/group_26#47]
Hey guys,

I have write up the docker file but I have not changed the README for instructions on testing. Here's how you can run it at the moment:

1. Make sure you are at the root of the project where the `Dockerfile` is present
2. Run `docker build -t group_26 .` This command builds the docker file and give it a tag name called group_26
3. Once the build above finishes, execute command `docker run -v FULL_PATH_TO_REPO_ROOT:/home/source -it --entrypoint bash group_26`. You want to replace `FULL_PATH_TO_REPO_ROOT` with the **absolute path** to the root of our current repository. You can obtain this by using `pwd`.
4. Once you have succeed in executing the commands above, you should be in the bash shell of the docker container. The default working directly should already be the root of our mounted project directory. You can try running `make clean` and `make all` to see if they can be successfully executed.

Please let me know if you need more help. Note that, if you are using Windows, `pwd` might not work and you might have additional issues mounting the volumes. In that case, you might want to refer to conversation on Slack on how to deal with those.

**Comment by arashshams** [comment]
Thanks @Andrew-Tan . This is great. I will put some non-technical comments down here and check Tiff's demos for some technical comments later on:
I will use " " to refer to your highlighting:
- Make sure you are in the root directory of the project where the "Dockerfile" exists.
- Run "docker build -t group_26" . This command builds the docker file. You can give it a tag name called "group_26".
- Once the build above finishes, execute command "docker run -v FULL_PATH_TO_REPO_ROOT:/home/source -it --entrypoint bash group_26". You may want to replace "FULL_PATH_TO_REPO_ROOT" with the absolute path to the root of our current repository. You can obtain this by using "pwd" command.
- Once you have succeeded in executing the commands above, you should be in the bash shell of the docker container. The default working directory should already be the root of our mounted project directory. You can try running "make clean" and "make all" to see if they can be successfully executed.

**Comment by Andrew-Tan** [comment]
Sure. Note that this is just to set you up so that you can use the interactive shell inside the container if you want to do something else inside the container. 

Eventually in README, we can use the one-liner demonstrated in the video if we only want to execute a single command.

**Comment by arashshams** [comment]
Oh I see, I thought these instructions might need to be posted.

**Comment by mmyz88** [comment]
Some issues regarding the instructions:
- `docker build -t group_26` needs to be `docker build -t group_26 .` (note the . at the end) if you are running local dockerfile, otherwise i got the "docker build" requires exactly 1 argument error
- I got this `ERRO[0000] failed to dial gRPC: unable to upgrade to h2c, received 500` error when I ran docker build for the first time. But I ran the same command again and everything seems to be working. Apparently this is some server error that has nothing to do with our dockerfile. See this thread: https://github.com/docker-library/docker/issues/71. Just noting here as an FYI

Other than that, the container works fine and I was able to get everything going inside the container

**Comment by Andrew-Tan** [comment]
> docker build -t group_26 needs to be docker build -t group_26 . (note the . at the end) if you are running local dockerfile, otherwise i got the "docker build" requires exactly 1 argument error

Yes. My original post does include the dot and it's an essential argument. You can also use pwd if you want (e.g. `docker build -t group_26 $(pwd)`.
