### ISSUE TITLE
Exponent check in reasoning paragraph

### ISSUE THREAD

**Issue by arashshams** [UBC-MDS/group_26#49]
V. Random Forest (the explanation paragraph -last line)

however the validation scores are not improved significantly (changes in the order of **10^-4** ---> in Jupyter: $10^{-4}$ ). According to above results, the model is overfitting with our data as the gap between the train and test scores is large.

**Comment by mmyz88** [comment]
Fixed. Changed 10--4 to $10^{-4}$
