### ISSUE TITLE
Peer Review - Deb

### ISSUE THREAD

**Issue by debanandasarkar** [UBC-MDS/group_26#51]
Hi Team, 

I quickly glanced through your release 0.2.0 and I really appreciate the job your team did. It was easy to review your project quickly as I felt it was constructed very efficiently. I liked the way README.md file was constructed. The objectives, dataset and analysis section tells me exactly what you are trying to achieve and I did not have to navigate to other links to get a high level understanding of your project.

Here are few minor points, I wanted to highlight:

EDA report: You have a SettingWithCopyWarning and I think you have already fixed it. Looks like the warning does not impact your analysis result, but it might throw off someone who does not have Python background 

Final report: Like README.md file, final report was laid out very well. It was really easy to go through the document. I want to highlight couple of minor points
- The link for model selection (https://ubc-mds.github.io/group_26/doc/model_selection.ipynb) did not open for me.
- I did not understood, why you choose SVR over Ridge. 
    - Yes, Ridge is fitting the training model more but it is generalising well on validation set. The gap between mean training score and validation score looks same for SVR and Ridge.
    - Also, Ridge would give you a good model interpretation and much less training and tuning time 

Code: The code construct is good and easy to understand.
- From the Makefile, I felt that you are generating EDA report on the entire data instead of train split only. If my assessment is right, you can mention that in EDA report or README.md

Cheers.

**Comment by mmyz88** [comment]
Thank you @debanandasarkar ! Good catch on the reports and the Makefile. We will likely make those changes. 

As for the model selection, it was not the final decision yet. The justification there was a bit weak I agree. However we are trying to add the stop_words argument into the estimators and that seems to make SVR more outstanding. I believe it will be more reasonable in our final report.

**Comment by debanandasarkar** [comment]
Thanks for the explanation for SVR. Makes perfect sense. I thought I was missing something and wanted to check with you.
