### ISSUE TITLE
Regarding Reflection and Improvements section

### ISSUE THREAD

**Issue by arashshams** [UBC-MDS/group_26#53]
Now that we are done with our prediction and analysis, we can examine the quality of our work. In fact, there are a few areas of improvement.

- We discarded the Author and id columns at the beginning. In fact, these columns may be influential features, especially Author. One major flaw of our dataset is that all reviews come from four critics. This makes it difficult to generalize to the broader audience. It would **be** better if we can obtain reviews from the general audiences. **(to be corrected)** , **also, maybe we would better change "flaw" part, to : An inherent problem with our dataset is that .....**
- There is risk of overfitting in our models. Based on the model selection results, all three candidate models have large gaps between training score and test scores. We have tuned the hyperparameters the best we can, yet the gap is still apparent. This might have to do with the nature of our dataset and model compatibility, and it requires further analysis. **(all good)**
- As mentioned above, our model did not capture the pattern where humans tend to give whole number scores. In the future, we can probably give more emphasis to predicting whole number scores, so that our model resembles more human behaviors. **(all good)**
- The sentiment feature **generated** with the NLTK package contained only neu and compound in our dataset. This is confusing and we have yet to understand this behavior. We included the feature regardless because it may still provide useful information. However, this is definitely a place we need to investigate further into. **(I suggest we delete this item, since we have already trusted the NLTK and this is what the package has given us, I mean nothing to dig into)**

**Comment by Andrew-Tan** [comment]
per our discussion, we think we might not need to delete the point for NLTK. So it's good enough to just  re-word the first point in **Reflection and Improvement**

**Comment by mmyz88** [comment]
Reworded first bullet-point in final report.
