### ISSUE TITLE
Peer review 0.2.0 release

### ISSUE THREAD

**Issue by sunsiche** [UBC-MDS/group_26#60]
Documentation: 
Is the project is properly documented and files are well organized.

Code: 
The code worked, but it took me some time to figure out the packages to be installed, it would be nice if a yaml file was available.

Analysis and reasoning: 
The EDA part is very interesting! In your final report, can you please mention the reason for which you choose Ridge, SVR and Random forest as your predictors? And why do we use RMSE scores to evaluate the models?

Communication:
The reports are clear and easy to follow.

Suggestions: 
The only feature engineering method used is CountVectorizer which gives words frequencies, the text message contains a lot more information than this, maybe exploring other feature engineering methods could be your future direction.

Have a great weekend!

**Comment by yzr1996** [comment]
> Documentation:
> Is the project is properly documented and files are well organized.
> 
> Code:
> The code worked, but it took me some time to figure out the packages to be installed, it would be nice if a yaml file was available.
> 
> Analysis and reasoning:
> The EDA part is very interesting! In your final report, can you please mention the reason for which you choose Ridge, SVR and Random forest as your predictors? And why do we use RMSE scores to evaluate the models?
> 
> Communication:
> The reports are clear and easy to follow.
> 
> Suggestions:
> The only feature engineering method used is CountVectorizer which gives words frequencies, the text message contains a lot more information than this, maybe exploring other feature engineering methods could be your future direction.
> 
> Have a great weekend!

Hi @sunsiche , thank you for your feedback. This week we added the dockerfile, and I believe it will solve the env problem. We are also optimizing our model selection part.

**Comment by Andrew-Tan** [comment]
We had a discussion previously about using MAPE. But later we've found that this metric won't work for our data, since our since our prediction contains zeros.
